#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /api/register
  controller: App\Controller\UserController::registerUser

login:
  path: /api/login
  controller: App\Controller\UserController::login

getMyAssets:
  path: /api/assets/getMyAsset
  controller: App\Controller\AssetController::getMyAssets

editAsset:
  path: /api/assets/editAsset
  controller: App\Controller\AssetController::editAsset

addAsset:
  path: /api/assets/addAsset
  controller: App\Controller\AssetController::addAsset

searchAsset:
  path: /api/assets/getAssetSearch
  controller: App\Controller\AssetController::getAssetSearch

getFriend:
  path: /friend/{iFriendId}
  controller: App\Controller\UserConnectionsController::getFriend
  methods:    GET

getFriends:
  path: /friends
  controller: App\Controller\UserConnectionsController::getFriends
  methods:    GET

sendFriendRequest:
  path: /user/request/{iUserId}
  controller: App\Controller\UserConnectionsController::sendFriendRequest
  methods:    POST

getFriendRequests:
  path: /friendRequests
  controller: App\Controller\UserConnectionsController::getFriendRequest
  methods:    GET

replyFriendRequest:
  path: /friendRequest/reply
  controller: App\Controller\UserConnectionsController::replyFriendRequest
  methods:    POST

deleteFriendship:
  path: /friend/delete/{iFriendId}
  controller: App\Controller\UserConnectionsController::deleteFriendship
  methods:    DELETE

getUserSearch:
  path: /search/{sSearch}
  controller: App\Controller\UserConnectionsController::getUserSearch
  methods:    GET

sendLoanRequest:
  path: /asset/request/{iAssetId}
  controller: App\Controller\LoanController::sendLoanRequest
  methods:    POST

getLoanRequest:
    path: /loanRequest
    controller: App\Controller\LoanController::getLoanRequest
    methods:    GET

getLoanRequestStatus:
  path: /loanStatus
  controller: App\Controller\LoanController::getLoanRequestStatus
  methods:    GET

replyLoanRequest:
  path: /loanRequest/reply
  controller: App\Controller\LoanController::replyLoanRequest
  methods:    POST

getAcceptedRequest:
  path: /loanAccepted
  controller: App\Controller\LoanController::getAcceptedRequest
  methods:    GET

getLoans:
  path: /loans
  controller: App\Controller\LoanController::getLoans
  methods:    GET

getAllUnavailableDates:
  path: /getAllUnavailableDates
  controller: App\Controller\LoanController::getAllUnavailableDates
  methods:    GET
