#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /api/register
  controller: App\Controller\UserController::registerUser

login:
  path: /api/login
  controller: App\Controller\UserController::login

getMyAssets:
  path: /api/assets/getMyAsset
  controller: App\Controller\AssetController::getMyAssets

editAsset:
  path: /api/assets/editAsset
  controller: App\Controller\AssetController::editAsset

addAsset:
  path: /api/assets/addAsset
  controller: App\Controller\AssetController::addAsset

searchAsset:
  path: /api/assets/getAssetSearch
  controller: App\Controller\AssetController::getAssetSearch

getFriend:
  path: /getFriend
  controller: App\Controller\UserConnectionsController::getFriend
  methods:    GET

getAllFriends:
  path: /getAllFriends
  controller: App\Controller\UserConnectionsController::getAllFriends
  methods:    GET

getAllFriendRequest:
  path: /getAllFriendRequest
  controller: App\Controller\UserConnectionsController::getAllFriendRequest
  methods:    GET

sendFriendRequest:
  path: /sendFriendRequest
  controller: App\Controller\UserConnectionsController::sendFriendRequest
  methods:    POST

replyFriendRequest:
  path: /replyFriendRequest
  controller: App\Controller\UserConnectionsController::replyFriendRequest
  methods:    POST

getUserSearch:
  path: /getUserSearch
  controller: App\Controller\UserConnectionsController::getUserSearch
  methods:    GET

deleteFriendship:
  path: /deleteFriendship
  controller: App\Controller\UserConnectionsController::deleteFriendship
  methods:    DELETE

changeLoanStatus:
  path: /changeLoanStatus
  controller: App\Controller\LoanController::changeLoanStatus
  methods:    POST

sendLoanRequest:
  path: /sendLoanRequest
  controller: App\Controller\LoanController::sendLoanRequest
  methods:    POST

getAllLoanRequest:
    path: /getAllLoanRequest
    controller: App\Controller\LoanController::getAllLoanRequest
    methods:    GET

getLoanRequestStatus:
  path: /getLoanRequestStatus
  controller: App\Controller\LoanController::getLoanRequestStatus
  methods:    GET

getAcceptedRequest:
  path: /getAcceptedRequest
  controller: App\Controller\LoanController::getAcceptedRequest
  methods:    GET

getAllLoans:
  path: /getAllLoans
  controller: App\Controller\LoanController::getAllLoans
  methods:    GET