#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#-------------------------------------------User--Finn Gundersen--------------------------------------------------

register:
  path: /api/register
  controller: App\Controller\UserController::registerUser
  methods: POST

login:
  path: /api/login/{sUsername}/{sPassword}
  controller: App\Controller\UserController::login
  methods: GET

editUser:
  path: /user/{iUserId}/edit
  controller: App\Controller\UserController::editUser
  methods: POST

getCurrentUser:
  path: /api/getCurrentUser
  controller: App\Controller\UserController::getCurrentUser

profileimageUpload:
  path: /profileimageUpload
  controller: App\Controller\UserController::profileimageUpload
  methods: POST

updatePassword:
  path: /updatePassword
  controller: App\Controller\UserController::updatePassword
  methods: POST

getUsers:
  path: /users
  controller: App\Controller\UserController::getUsers
  methods: GET

getUserAmount:
  path: /users/amount
  controller: App\Controller\UserController::getUserAmount
  methods: GET

#-------------------------------------------Assets--John-Berge Grimaas--------------------------------------------------
getAssetSearch:
  path: /assets/search/{userId}/{search}
  controller: App\Controller\AssetController::getAssetSearch
  methods: GET

getAssetType:
  path: /assets/getAssetType/{userId}/{typeId}
  controller: App\Controller\AssetController::getAssetType
  methods: GET

getMyAssets:
  path: /assets/getMyAsset/{userId}
  controller: App\Controller\AssetController::getMyAssets
  methods: GET

getAsset:
  path: /assets/getAsset/{assetId}
  controller: App\Controller\AssetController::getAsset
  methods: GET

addAsset:
  path: /assets/addAsset
  controller: App\Controller\AssetController::addAsset
  methods: POST

editAsset:
  path: /assets/editAsset/{userId}/{assetId}
  controller: App\Controller\AssetController::editAsset
  methods: PUT

getMainImage:
  path: /assetsImage/getMainImage/{assetId}
  controller: App\Controller\AssetImageController::getMainImage
  methods: GET

addImage:
  path: /assetsImage/addImage/{userId}/{assetId}
  controller: App\Controller\AssetImageController::addImage
  methods: POST

assetAvailability:
  path: /loans/availability/{assetId}
  controller: App\Controller\LoanController::assetAvailability
  methods: GET

getAssetTypes:
  path: /assets/type/{iCatId}
  controller: App\Controller\AssetTypeController::getAssetTypes
  methods: GET

getAssetCategories:
  path: /assets/category
  controller: App\Controller\AssetTypeController::getAssetCategories
  methods: GET

getAllAssetTypes:
  path: /assets/AllTypes
  controller: App\Controller\AssetTypeController::getAllAssetTypes
  methods: GET

removeAsset:
  path: /assets/removeAsset/{assetId}
  controller: App\Controller\AssetController::removeAsset
  methods: DELETE

getIndividAssetAmount:
  path: /assets/IndividAssetAmount/{userId}
  controller: App\Controller\AssetController::getIndividAssetAmount
  methods: GET

getAssetAmount:
  path: /assets/AssetAmount
  controller: App\Controller\AssetController::getAssetAmount
  methods: GET

getUsersAssets:
  path: /assets/getUsersAssets/{userId1}/{userId2}
  controller: App\Controller\AssetController::getUsersAssets
  methods: GET
  
setPublished:
  path: /setPublished/{userId}/{assetId}/{published}
  controller: App\Controller\AssetController::setPublished
  methods: POST

#---------------------------------------------Chat--John-Berge Grimaas--------------------------------------------------

getChat:
  path: /users/chat/{userId1}/{userId2}
  controller: App\Controller\ChatController::getChat
  methods: GET

writeMessage:
  path: /users/writeMessage/{userId1}/{userId2}
  controller: App\Controller\ChatController::writeMessage
  methods: POST

getChats:
  path: /users/getChats/{userId}
  controller: App\Controller\ChatController::getChats
  methods: GET

#-------------------------------------------Rating--John-Berge Grimaas--------------------------------------------------


getAverageAssetRating:
  path: /assets/{assetId}/AverageRating
  controller: App\Controller\RatingController::getAverageAssetRating
  methods: GET

rateAsset:
  path: /assets/{assetId}/rateAsset/{userId}/{newRating}
  controller: App\Controller\RatingController::rateAsset
  methods: POST

#------------------------------------------Logging--John-Berge Grimaas--------------------------------------------------

logging:
  path: /logging/{userId}/{functionName}
  controller: App\Controller\UtilController::logging
  methods: POST

getLogg:
  path: /logging/{userId}
  controller: App\Controller\UtilController::getLogg
  methods: GET

getLevels:
  path: /getLevels
  controller: App\Controller\UtilController::getLevels
  methods: GET

getLevel:
  path: /getLevel
  controller: App\Controller\UtilController::getLevel
  methods: GET

setLevel:
  path: /setLevel/{newLevel}
  controller: App\Controller\UtilController::setLevel
  methods: POST

#---------------------------------------------UserConnections--Nicole Bendu---------------------------------------------

getFriend:
  path: /user/{iUserId}/friend/{iFriendId}
  controller: App\Controller\UserConnectionsController::getFriend
  methods: GET

getFriends:
  path: /user/{iUserId}/friends
  controller: App\Controller\UserConnectionsController::getFriends
  methods: GET

sendFriendRequest:
  path: /user/{iUserId}/request/{iFriendId}
  controller: App\Controller\UserConnectionsController::sendFriendRequest
  methods: POST

getFriendRequests:
  path: /user/{iUserId}/friendRequests
  controller: App\Controller\UserConnectionsController::getFriendRequest
  methods: GET

replyFriendRequest:
  path: /user/{iUserId}/friendRequest/{iFriendId}/{iStatus}
  controller: App\Controller\UserConnectionsController::replyFriendRequest
  methods: POST

deleteFriendship:
  path: /user/{iUserId}/friend/{iFriendId}/delete
  controller: App\Controller\UserConnectionsController::deleteFriendship
  methods: POST

getUserSearch:
  path: /user/{iUserId}/search/{sSearch}
  controller: App\Controller\UserConnectionsController::getUserSearch
  methods:    GET

#---------------------------------------------------Loans--Nicole Bendu-------------------------------------------------

sendLoanRequest:
  path: /user/{iUserId}/asset/{iAssetId}/request
  controller: App\Controller\LoanController::sendLoanRequest
  methods: POST

getLoanRequest:
    path: /user/{iUserId}/loanRequest
    controller: App\Controller\LoanController::getLoanRequest
    methods:    GET

replyLoanRequests:
  path: /user/{iUserId}/loanRequest/{iLoanId}/{iStatus}
  controller: App\Controller\LoanController::replyLoanRequest
  methods:    POST

getAcceptedRequest:
  path: /user/{iUserId}/loanAccepted
  controller: App\Controller\LoanController::getAcceptedRequests
  methods: GET

getSentRequest:
  path: /user/{iUserId}/loanSent
  controller: App\Controller\LoanController::getSentRequests
  methods: GET

getDeniedRequest:
  path: /user/{iUserId}/loanDenied
  controller: App\Controller\LoanController::getDeniedRequests
  methods: GET
  
getLoans:
  path: /user/{iUserId}/loans
  controller: App\Controller\LoanController::getLoans
  methods: GET

#---------------------------------------------------Report--Nicole Bendu-------------------------------------------------

makeReport:
  path: /user/{iUserId}/report/{iUserId2}
  controller: App\Controller\UnwantedBehaviorReportsController::report
  methods: POST

getReports:
  path: /getReports
  controller: App\Controller\UnwantedBehaviorReportsController::getReports
  methods: GET

getReportAmount:
  path: /report/amount
  controller: App\Controller\UnwantedBehaviorReportsController::getReportAmount
  methods: GET

