#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /api/register
  controller: App\Controller\UserController::registerUser

login:
  path: /api/login
  controller: App\Controller\UserController::login

getMyAssets:
  path: /api/assets/getMyAsset
  controller: App\Controller\AssetController::getMyAssets

editAsset:
  path: /api/assets/editAsset
  controller: App\Controller\AssetController::editAsset

addAsset:
  path: /api/assets/addAsset
  controller: App\Controller\AssetController::addAsset

searchAsset:
  path: /api/assets/getAssetSearch
  controller: App\Controller\AssetController::getAssetSearch

getAsset:
  path: /api/assets/getAsset
  controller: App\Controller\AssetController::getAsset

getFriend:
  path: /getFriend
  controller: App\Controller\UserConnectionsController::getFriend


getAllFriends:
  path: /getAllFriends
  controller: App\Controller\UserConnectionsController::getAllFriends


getAllFriendRequest:
  path: /getAllFriendRequest
  controller: App\Controller\UserConnectionsController::getAllFriendRequest


sendFriendRequest:
  path: /sendFriendRequest
  controller: App\Controller\UserConnectionsController::sendFriendRequest


replyFriendRequest:
  path: /replyFriendRequest
  controller: App\Controller\UserConnectionsController::replyFriendRequest


getUserSearch:
  path: /getUserSearch
  controller: App\Controller\UserConnectionsController::getUserSearch


deleteFriendship:
  path: /deleteFriendship
  controller: App\Controller\UserConnectionsController::deleteFriendship


changeLoanStatus:
  path: /changeLoanStatus
  controller: App\Controller\LoanController::changeLoanStatus


sendLoanRequest:
  path: /sendLoanRequest
  controller: App\Controller\LoanController::sendLoanRequest


getAllLoanRequest:
    path: /getAllLoanRequest
    controller: App\Controller\LoanController::getAllLoanRequest


getLoanRequestStatus:
  path: /getLoanRequestStatus
  controller: App\Controller\LoanController::getLoanRequestStatus


getAcceptedRequest:
  path: /getAcceptedRequest
  controller: App\Controller\LoanController::getAcceptedRequest


getAllLoans:
  path: /getAllLoans
  controller: App\Controller\LoanController::getAllLoans


getCurrentUser:
    path: /api/getCurrentUser
    controller: App\Controller\UserController::getCurrentUser