#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /api/register
  controller: App\Controller\UserController::registerUser
  methods: POST

login:
  path: /api/login/{sUsername}/{sPassword}
  controller: App\Controller\UserController::login
  methods: GET

#---------------------------------------------------John-Berge Grimaas--------------------------------------------------
getAssetSearch:
  path: /assets/search/{userId}/{search}
  controller: App\Controller\AssetController::getAssetSearch
  methods: GET

getMyAssets:
  path: /assets/getMyAsset/{userId}
  controller: App\Controller\AssetController::getMyAssets
  methods: GET

getAsset:
  path: /assets/getAsset/{assetId}
  controller: App\Controller\AssetController::getAsset
  methods: GET

addAsset:
  path: /assets/addAsset
  controller: App\Controller\AssetController::addAsset
  methods: POST

editAsset:
  path: /assets/editAsset/{userId}/{assetId}
  controller: App\Controller\AssetController::editAsset
  methods: GET

getMainImage:
  path: /assetsImage/getMainImage/{assetId}
  controller: App\Controller\AssetImageController::getMainImage
  methods: GET

addImage:
  path: /assetsImage/addImage/{userId}/{assetId}
  controller: App\Controller\AssetImageController::addImage
  methods: POST

assetAvailability:
  path: /loans/availability/{assetId}
  controller: App\Controller\LoanController::assetAvailability
  methods: GET

#---------------------------------------------UserConnections--Nicole Bendu---------------------------------------------
getFriend:
  path: /user/{iUserId}/friend/{iFriendId}
  controller: App\Controller\UserConnectionsController::getFriend
  methods: GET

getFriends:
  path: /user/{iUserId}/friends
  controller: App\Controller\UserConnectionsController::getFriends
  methods: GET

sendFriendRequest:
  path: /user/{iUserId}/request/{iFriendId}
  controller: App\Controller\UserConnectionsController::sendFriendRequest
  methods: POST

getFriendRequests:
  path: /user/{iUserId}/friendRequests
  controller: App\Controller\UserConnectionsController::getFriendRequest
  methods: GET

replyFriendRequest:
  path: /user/{iUserId}/friendRequest/{iFriendId}/{iStatus}
  controller: App\Controller\UserConnectionsController::replyFriendRequest
  methods: POST

deleteFriendship:
  path: /user/{iUserId}/friend/{iFriendId}/delete
  controller: App\Controller\UserConnectionsController::deleteFriendship
  methods: POST

getUserSearch:
  path: /user/{iUserId}/search/{sSearch}
  controller: App\Controller\UserConnectionsController::getUserSearch
  methods:    GET

#---------------------------------------------------Loans--Nicole Bendu-------------------------------------------------
sendLoanRequest:
  path: /user/{iUserId}/asset/{iAssetId}/request
  controller: App\Controller\LoanController::sendLoanRequest
  methods: POST

getLoanRequest:
    path: /user/{iUserId}/loanRequest
    controller: App\Controller\LoanController::getLoanRequest
    methods:    GET

getLoanRequestStatus:
  path: /user/{iUserId}/loanRequest/status
  controller: App\Controller\LoanController::getLoanRequestStatus
  methods: GET

replyLoanRequests:
  path: /user/{iUserId}/loanRequest/{iLoanId}/{iStatus}
  controller: App\Controller\LoanController::replyLoanRequest
  methods:    POST

getAcceptedRequest:
  path: /user/{iUserId}/loanAccepted
  controller: App\Controller\LoanController::getAcceptedRequests
  methods: GET
  
getLoans:
  path: /user/{iUserId}/loans
  controller: App\Controller\LoanController::getLoans
  methods: GET

getCurrentUser:
    path: /api/getCurrentUser
    controller: App\Controller\UserController::getCurrentUser

